const httpstatusCodes = {
  // SUCCESSFUL RESPONSES
  OK: 200,
  RESOURCE_CREATED: 201,

  // CLIENT ERROR RESPONSES
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  LARGE_PAYLOAD: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,

  // SERVER ERROR
  INTERNAL_SERVER_ERROR: 500,
};
module.exports = httpstatusCodes;
